Fix/outofmemory (#44)
* Updated code to new streaming (de)serializer from vibe.

* Fix for java.lang.NoSuchMethodError error.

* Update to non-local non-SHAPSHOT version of VIBE.

* Updated version in HTML file.

* Reduced Docker memory in README back to 4GB.

* Added try-with-resources in for correct closing of stream.

* Reformatted code.

* Fixed code smells.

* Fixed code smell.